import type { Metadata } from 'next'
import '../styles/globals.css'
import { Inter, Inter_Tight } from 'next/font/google'

import Providers from './providers'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import { siteDescription, siteName, siteTitle, siteUrl } from '../lib/site'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans',
})

/*
 * Heading font. The style gate rejected the editorial serif that used to sit
 * here: a warm cream ground plus a serif display plus a terracotta accent is
 * the recognisable look of a generated template, and the site had all three.
 * Inter Tight at a tight negative tracking replaces it.
 */
const interTight = Inter_Tight({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-display',
})

/*
 * Metadata API — replaces the old app/header.tsx, which used the abandoned
 * Next 13-beta `head.tsx` convention and was rendered as a sibling of <body>.
 *
 * The Open Graph and Twitter blocks are what a pasted link renders as in
 * Slack, LinkedIn, WhatsApp and iMessage. Without them the site arrived as a
 * bare URL, which is a poor showing for a link whose whole job is to be
 * shared with people hiring.
 *
 * The card image itself is generated by app/opengraph-image.tsx; Next wires
 * it in and fills in the url, type and dimensions, so it is not listed here.
 */
export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: siteTitle,
  description: siteDescription,
  icons: { icon: '/favicon.png' },
  alternates: { canonical: '/' },
  openGraph: {
    type: 'website',
    url: '/',
    siteName,
    title: siteTitle,
    description: siteDescription,
    locale: 'en_US',
  },
  twitter: {
    card: 'summary_large_image',
    title: siteTitle,
    description: siteDescription,
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    /*
     * suppressHydrationWarning is required: next-themes writes the theme class
     * onto <html> before React hydrates, so server and client markup differ
     * here by design.
     */
    <html lang="en" className={`${inter.variable} ${interTight.variable}`} suppressHydrationWarning>
      <body className="min-h-screen bg-[var(--background)] text-[var(--foreground)] antialiased">
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
